### ISSUE TITLE
Change log between Base Firmware Versions

### ISSUE THREAD

**Issue by jipvankuijk** [BotoX/xiaomi-m365-firmware-patcher#20]
Hey everyone,

Does anyone have any idea what the changelog is between 1.3.0/1.3.4/1.3.8/1.4.0? I know you shouldn't update to 1.4.1 because it blocks unknown firmware. 

Also why is 1.3.8 smoother than 1.4.0?

Thanks in advance!

**Comment by Neophytez** [comment]
Official change log: 1.3.4
- Fixed in the moving vehicle when unlocking, the alarm non-stop problem.
- Fixed the problem when the vehicle was unlocked and the alarm was kept.

Official change log: 1.3.3
- Add lock and alarm function.
- Add the youth serial number.
- Add international version to the serial number.
- Increase the taillight light option.

Official change log: 1.3.2
- The correction of a certain case, cannot be IAP problem.
- Fixed in some specific circumstances, can not be IAP problem.
