### ISSUE TITLE
Please add option set KERS custom value

### ISSUE THREAD

**Issue by andris155** [BotoX/xiaomi-m365-firmware-patcher#54]
I tested the new beta firmware. The KERS is not changed if I changed speed control params.
If changed the not bate firmware Motor power constant - Also changed KERS value.

I tested a KERS setting on the application. The weak is too weak and medium is too strong brake. :(
I need a setting to set custom value between weak and medium.

**Comment by BotoX** [comment]
KERS is garbage, don't use it.
The values can be changed for KERS too but as I said, it's trash.
Convince me why you'd want to use it when you can just use your brake lever?

**Comment by andris155** [comment]
The KERS is very useful if I don't need hard brake.

**Comment by tibrocks** [comment]
To be honest the best decision was to disable KERS via custom firmware as it had improved the ride considerably. KERS will not bring you to a full stop plus you still get some energy recovery when braking with mechanical brake.

**Comment by MarlonMrN** [comment]
Probably the best question is: what's worth more, leave the scooter "on neutral" for some time or have kers to recover energy downhill (assuming it can go as fast as 40km/h downhill and save power after that because scooter will not need to accelerate immediately after the hill ends)

I used kers on and off, the battery consumption was almost the same (if not less with kers off).

I will test it someday the same settings with kers on/off and check those values.

**Comment by MatG0** [comment]
It would be nice to have possibility to edit 3 kers modes. Weak -> disabled, medium-> weak, strong -> custom value

**Comment by Adorfer** [comment]
the question is not "what is best value", but "why not make a customizable option."

(otherwise we could discuss for nearly all options of the patcher the "ideal value" and afterwards delete the complete configuration part, since everybody agreed to the optimal settings....)
